package ru.yandex.practicum.filmorate.storage.dao;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class ManagerDatabaseDao {
    private final JdbcTemplate jdbcTemplate;

    @Autowired
    public ManagerDatabaseDao(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public void createAllTabs() {
        String user = "create TABLE IF NOT EXISTS PUBLIC.\"user\"(\n" +
                "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
                "\temail VARCHAR(255) NOT NULL,\n" +
                "\tlogin VARCHAR(255) NOT NULL,\n" +
                "\tname VARCHAR(255),\n" +
                "\tbirthday DATE NOT NULL\n" +
                ");";
        jdbcTemplate.update(user);

        String friendship = "create TABLE IF NOT EXISTS PUBLIC.\"friendship\"(\n" +
                "\tuser_id BIGINT NOT NULL REFERENCES PUBLIC.\"user\"(id),\n" +
                "\tfriend_id BIGINT NOT NULL REFERENCES PUBLIC.\"user\"(id),\n" +
                "\tis_approved BOOLEAN\n" +
                ");";
        jdbcTemplate.update(friendship);

        String mpa = "create TABLE IF NOT EXISTS PUBLIC.\"mpa\" (\n" +
                "    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
                "    name          VARCHAR(10) NOT NULL UNIQUE\n" +
                ");";
        jdbcTemplate.update(mpa);

        String film = "create TABLE IF NOT EXISTS PUBLIC.\"film\"(\n" +
                "\tid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
                "\tname VARCHAR(255) NOT NULL,\n" +
                "\tdescription VARCHAR(200),\n" +
                "\trelease_date DATE NOT NULL,\n" +
                "\tduration INTEGER NOT NULL,\n" +
                "\trate BIGINT,\n" +
                "\tmpa_id INTEGER REFERENCES PUBLIC.\"mpa\"(id)\n" +
                ");";
        jdbcTemplate.update(film);

        String like = "create TABLE IF NOT EXISTS PUBLIC.\"like\"(\n" +
                "\tfilm_id BIGINT NOT NULL REFERENCES PUBLIC.\"film\"(id),\n" +
                "\tuser_id BIGINT NOT NULL REFERENCES PUBLIC.\"user\"(id)\n" +
                ");";
        jdbcTemplate.update(like);

        String genre = "create TABLE IF NOT EXISTS PUBLIC.\"genre\"(\n" +
                "\tid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
                "\tname VARCHAR(255) NOT NULL UNIQUE\n" +
                ");";
        jdbcTemplate.update(genre);

        String filmGenres = "create TABLE IF NOT EXISTS PUBLIC.\"film_genres\"(\n" +
                "\tfilm_id BIGINT NOT NULL REFERENCES PUBLIC.\"film\"(id)  ON DELETE CASCADE,\n" +
                "\tgenre_id INTEGER NOT NULL REFERENCES PUBLIC.\"genre\"(id)\n" +
                ");";
        jdbcTemplate.update(filmGenres);

        String insertMpa = "MERGE INTO PUBLIC.\"mpa\" (id, name)\n" +
                "VALUES (1, 'G'),\n" +
                "       (2, 'PG'),\n" +
                "       (3, 'PG-13'),\n" +
                "       (4, 'R'),\n" +
                "       (5, 'NC-17');";
        jdbcTemplate.update(insertMpa);

        String insertGenre = "MERGE INTO PUBLIC.\"genre\" (id, name)\n" +
                "VALUES (1, 'Комедия'),\n" +
                "       (2, 'Драма'),\n" +
                "       (3, 'Мультфильм'),\n" +
                "       (4, 'Триллер'),\n" +
                "       (5, 'Документальный'),\n" +
                "       (6, 'Боевик');";
        jdbcTemplate.update(insertGenre);

    }

    public void deleteAllTabs() {
        deleteAllTabsAssociatedWithFilmTable();

        String deletionFriendshipSqlRequest = "DROP TABLE PUBLIC.\"friendship\"";
        String deletionUserSqlRequest = "DROP TABLE PUBLIC.\"user\"";

        jdbcTemplate.update(deletionFriendshipSqlRequest);
        jdbcTemplate.update(deletionUserSqlRequest);
    }

    public void deleteAllTabsAssociatedWithUserTable() {
        String deletionLikesSqlRequest = "DROP TABLE PUBLIC.\"like\"";
        String deletionFriendshipSqlRequest = "DROP TABLE PUBLIC.\"friendship\"";
        String deletionUserSqlRequest = "DROP TABLE PUBLIC.\"user\"";

        jdbcTemplate.update(deletionLikesSqlRequest);
        jdbcTemplate.update(deletionFriendshipSqlRequest);
        jdbcTemplate.update(deletionUserSqlRequest);
    }

    public void deleteAllTabsAssociatedWithFilmTable() {
        String deletionLikesSqlRequest = "DROP TABLE PUBLIC.\"film_genres\"";
        String deletionFriendshipSqlRequest = "DROP TABLE PUBLIC.\"genre\"";
        String deletionLikeSqlRequest = "DROP TABLE PUBLIC.\"like\"";
        String deletionFilmSqlRequest = "DROP TABLE PUBLIC.\"film\"";
        String deletionMpaSqlRequest = "DROP TABLE PUBLIC.\"mpa\"";

        jdbcTemplate.update(deletionLikesSqlRequest);
        jdbcTemplate.update(deletionFriendshipSqlRequest);
        jdbcTemplate.update(deletionLikeSqlRequest);
        jdbcTemplate.update(deletionFilmSqlRequest);
        jdbcTemplate.update(deletionMpaSqlRequest);
    }
}
