DROP TABLE IF EXISTS PUBLIC."film_genres";
DROP TABLE IF EXISTS PUBLIC."genres";
DROP TABLE IF EXISTS PUBLIC."likes";
DROP TABLE IF EXISTS PUBLIC."films";
DROP TABLE IF EXISTS PUBLIC."mpa";
DROP TABLE IF EXISTS PUBLIC."friendships";
DROP TABLE IF EXISTS PUBLIC."users";